
package com.bluetech.protech.pojo;
// Generated Aug 19, 2024, 4:31:59 PM by Hibernate Tools 4.3.6.Final


import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * TbAirlineTravelexpensedetails generated by hbm2java
 */
@Entity
@Table(name = "tb_airline_travelexpensedetails", catalog = "airline")
public class TbAirlineTravelexpensedetails implements java.io.Serializable
{

    private Integer id;
    private TbAirlineCoordinates tbAirlineCoordinatesByAp3id;
    private TbAirlineCoordinates tbAirlineCoordinatesByAp1id;
    private TbAirlineCoordinates tbAirlineCoordinatesByAp2id;
    private TbAirlineFxRates tbAirlineFxRates;
    private Integer staffId;
    private String name;
    private String ticketNo;
    private Integer noOfTickets;
    private String route;
    private String returnStatus;
    private String systemType;
    private String airline;
    private Date flown;
    private String issued;
    private Double mileage;

    private String entitlement;
    private BigDecimal base;
    private BigDecimal taxes;
    private BigDecimal total;
    private BigDecimal totalLc;
    private Integer zone;
    private BigDecimal fareY;
    private BigDecimal fareFj;
    private BigDecimal fare;
    private BigDecimal hypDiscount;
    private BigDecimal value;
    private BigDecimal discount;
    private BigDecimal taxableWage;
    private String comments;
    private boolean enable;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId()
    {

        return this.id;
    }

    public void setId(Integer id)
    {

        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ap3Id", nullable = true)
    public TbAirlineCoordinates getTbAirlineCoordinatesByAp3id()
    {

        return this.tbAirlineCoordinatesByAp3id;
    }

    public void setTbAirlineCoordinatesByAp3id(TbAirlineCoordinates tbAirlineCoordinatesByAp3id)
    {

        this.tbAirlineCoordinatesByAp3id = tbAirlineCoordinatesByAp3id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ap1Id", nullable = true)
    public TbAirlineCoordinates getTbAirlineCoordinatesByAp1id()
    {

        return this.tbAirlineCoordinatesByAp1id;
    }

    public void setTbAirlineCoordinatesByAp1id(TbAirlineCoordinates tbAirlineCoordinatesByAp1id)
    {

        this.tbAirlineCoordinatesByAp1id = tbAirlineCoordinatesByAp1id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ap2Id", nullable = true)
    public TbAirlineCoordinates getTbAirlineCoordinatesByAp2id()
    {

        return this.tbAirlineCoordinatesByAp2id;
    }

    public void setTbAirlineCoordinatesByAp2id(TbAirlineCoordinates tbAirlineCoordinatesByAp2id)
    {

        this.tbAirlineCoordinatesByAp2id = tbAirlineCoordinatesByAp2id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "currencyID", nullable = true)
    public TbAirlineFxRates getTbAirlineFxRates()
    {

        return this.tbAirlineFxRates;
    }

    public void setTbAirlineFxRates(TbAirlineFxRates tbAirlineFxRates)
    {

        this.tbAirlineFxRates = tbAirlineFxRates;
    }

    @Column(name = "staffId")
    public Integer getStaffId()
    {

        return this.staffId;
    }

    public void setStaffId(Integer staffId)
    {

        this.staffId = staffId;
    }

    @Column(name = "name", length = 100)
    public String getName()
    {

        return this.name;
    }

    public void setName(String name)
    {

        this.name = name;
    }

    @Column(name = "ticketNo")
    public String getTicketNo()
    {

        return this.ticketNo;
    }

    public void setTicketNo(String ticketNo)
    {

        this.ticketNo = ticketNo;
    }

    @Column(name = "noOfTickets")
    public Integer getNoOfTickets()
    {

        return this.noOfTickets;
    }

    public void setNoOfTickets(Integer noOfTickets)
    {

        this.noOfTickets = noOfTickets;
    }

    @Column(name = "route", length = 50)
    public String getRoute()
    {

        return this.route;
    }

    public void setRoute(String route)
    {

        this.route = route;
    }

    @Column(name = "returnStatus", length = 50)
    public String getReturnStatus()
    {

        return returnStatus;
    }

    public void setReturnStatus(String returnStatus)
    {

        this.returnStatus = returnStatus;
    }

    @Column(name = "systemType", length = 50)
    public String getSystemType()
    {

        return systemType;
    }

    public void setSystemType(String systemType)
    {

        this.systemType = systemType;
    }

    @Column(name = "airline", length = 50)
    public String getAirline()
    {

        return this.airline;
    }

    public void setAirline(String airline)
    {

        this.airline = airline;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "flown", length = 19)
    public Date getFlown()
    {

        return this.flown;
    }

    public void setFlown(Date flown)
    {

        this.flown = flown;
    }

    @Column(name = "mileage")
    public Double getMileage()
    {

        return mileage;
    }

    public void setMileage(Double mileage)
    {

        this.mileage = mileage;
    }

    @Column(name = "issued", length = 50)
    public String getIssued()
    {

        return this.issued;
    }

    public void setIssued(String issued)
    {

        this.issued = issued;
    }

    @Column(name = "entitlement", length = 50)
    public String getEntitlement()
    {

        return this.entitlement;
    }

    public void setEntitlement(String entitlement)
    {

        this.entitlement = entitlement;
    }

    @Column(name = "base", precision = 10)
    public BigDecimal getBase()
    {

        return this.base;
    }

    public void setBase(BigDecimal base)
    {

        this.base = base;
    }

    @Column(name = "taxes", precision = 10)
    public BigDecimal getTaxes()
    {

        return this.taxes;
    }

    public void setTaxes(BigDecimal taxes)
    {

        this.taxes = taxes;
    }

    @Column(name = "total", precision = 10)
    public BigDecimal getTotal()
    {

        return this.total;
    }

    public void setTotal(BigDecimal total)
    {

        this.total = total;
    }

    @Column(name = "totalLC", precision = 10)
    public BigDecimal getTotalLc()
    {

        return this.totalLc;
    }

    @Column(name = "zone", length = 11)
    public Integer getZone()
    {

        return this.zone;
    }

    public void setZone(Integer zone)
    {

        this.zone = zone;
    }

    public void setTotalLc(BigDecimal totalLc)
    {

        this.totalLc = totalLc;
    }

    @Column(name = "fareY", precision = 10)
    public BigDecimal getFareY()
    {

        return this.fareY;
    }

    public void setFareY(BigDecimal fareY)
    {

        this.fareY = fareY;
    }

    @Column(name = "fareFJ", precision = 10)
    public BigDecimal getFareFj()
    {

        return this.fareFj;
    }

    public void setFareFj(BigDecimal fareFj)
    {

        this.fareFj = fareFj;
    }

    @Column(name = "fare", precision = 10)
    public BigDecimal getFare()
    {

        return this.fare;
    }

    public void setFare(BigDecimal fare)
    {

        this.fare = fare;
    }

    @Column(name = "value", precision = 10)
    public BigDecimal getValue()
    {

        return this.value;
    }

    public void setValue(BigDecimal value)
    {

        this.value = value;
    }

    @Column(name = "hypDiscount", precision = 10)
    public BigDecimal getHypDiscount()
    {

        return this.hypDiscount;
    }

    public void setHypDiscount(BigDecimal hypDiscount)
    {

        this.hypDiscount = hypDiscount;
    }

    @Column(name = "discount", precision = 10)
    public BigDecimal getDiscount()
    {

        return this.discount;
    }

    public void setDiscount(BigDecimal discount)
    {

        this.discount = discount;
    }

    @Column(name = "taxableWage", precision = 10)
    public BigDecimal getTaxableWage()
    {

        return this.taxableWage;
    }

    public void setTaxableWage(BigDecimal taxableWage)
    {

        this.taxableWage = taxableWage;
    }

    @Column(name = "comments", length = 500)
    public String getComments()
    {

        return this.comments;
    }

    public void setComments(String comments)
    {

        this.comments = comments;
    }

    @Column(name = "enable", nullable = false)
    public boolean isEnable()
    {

        return this.enable;
    }

    public void setEnable(boolean enable)
    {

        this.enable = enable;
    }

}
