package com.bluetech.protech.pojo;
// Generated Aug 19, 2024, 4:31:59 PM by Hibernate Tools 4.3.6.Final


import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * TbAirlineBarinrates generated by hbm2java
 */
@Entity
@Table(name = "tb_airline_barinrates", catalog = "airline")
public class TbAirlineBarinrates implements java.io.Serializable
{

    private Integer id;
    private String country;
    private Integer year;
    private double mileage;
    private Integer zone;
    private BigDecimal value;
    private String stbyDiscount;
    private BigDecimal zew;
    private boolean enable;

    public TbAirlineBarinrates()
    {}

    public TbAirlineBarinrates(boolean enable)
    {

        this.enable = enable;
    }

    public TbAirlineBarinrates(String country, Integer year, double mileage, Integer zone,
            BigDecimal value, String stbyDiscount, BigDecimal zew, boolean enable)
    {

        this.country = country;
        this.year = year;
        this.mileage = mileage;
        this.zone = zone;
        this.value = value;
        this.stbyDiscount = stbyDiscount;
        this.zew = zew;
        this.enable = enable;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId()
    {

        return this.id;
    }

    public void setId(Integer id)
    {

        this.id = id;
    }

    @Column(name = "country", length = 50)
    public String getCountry()
    {

        return this.country;
    }

    public void setCountry(String country)
    {

        this.country = country;
    }

    @Column(name = "year")
    public Integer getYear()
    {

        return this.year;
    }

    public void setYear(Integer year)
    {

        this.year = year;
    }

    @Column(name = "mileage")
    public double getMileage()
    {

        return this.mileage;
    }

    public void setMileage(double mileage)
    {

        this.mileage = mileage;
    }

    @Column(name = "zone")
    public Integer getZone()
    {

        return this.zone;
    }

    public void setZone(Integer zone)
    {

        this.zone = zone;
    }

    @Column(name = "value", precision = 10)
    public BigDecimal getValue()
    {

        return this.value;
    }

    public void setValue(BigDecimal value)
    {

        this.value = value;
    }

    @Column(name = "stbyDiscount", length = 10)
    public String getStbyDiscount()
    {

        return this.stbyDiscount;
    }

    public void setStbyDiscount(String stbyDiscount)
    {

        this.stbyDiscount = stbyDiscount;
    }

    @Column(name = "zew", precision = 10)
    public BigDecimal getZew()
    {

        return this.zew;
    }

    public void setZew(BigDecimal zew)
    {

        this.zew = zew;
    }

    @Column(name = "enable", nullable = false)
    public boolean isEnable()
    {

        return this.enable;
    }

    public void setEnable(boolean enable)
    {

        this.enable = enable;
    }

}
